### ISSUE TITLE
Gradient_rehearsal++ is missing

### ISSUE THREAD

**Issue by JosephKJ** [rahafaljundi/Gradient-based-Sample-Selection#3]
https://github.com/rahafaljundi/Gradient-based-Sample-Selection/blob/8c54db378e1bfec604413c892ad7577eb885f32e/Cifar_10.sh#L56

`Gradient_rehearsal++` is missing from `./model/`

**Comment by phquang** [comment]
I am able to run GSS_Greedy by changing` --model Gradient_rehearsal++`  to `--model GSS_Greedy`

**Comment by JosephKJ** [comment]
Hi @phquang , true, but that doesn't guarantee the reported results in the paper.

**Comment by rahafaljundi** [comment]
Hi, gradient rehearsal++ is the same as GSS Greedy.  It is just the name I
used before 😊

**Comment by JosephKJ** [comment]
Great! Thanks for confirming, @rahafaljundi!
